### ISSUE TITLE
common.pyについて

### ISSUE THREAD

**Issue by ghost** [hayatoito/google-2015-step-tsp#11]
output_*.csvで、数字が打たれていますが、それがどこから決定されているものであるのかを探していた際に
common.pyの
def format_solution(solution):
    return 'index\n' + '\n'.join(map(str, solution))

この関数のstrが何なのかわからなくなってしまいました。
教えていただけると嬉しいです。

**Comment by hayatoito** [comment]
`str` は数値を文字列に変換するために使用してます。

``` python
n = 123
print(type(n))

s = str(n)
print(type(s))
```

としてみれば数値が文字列に変換されていることがわかるはず。

ちなみに、`map` はいわゆる高階関数です。こんな感じ ↓

``` python
list_of_numbers = [1, 2, 3]

list_of_strings = []
for n in list_of_numbers:
  list_of_strings.append(str(n))

assert list_of_strings == ['1', '2', '3']

# map  を使って一行で書くなら
assert list(map(str, list_of_numbers)) == ['1', '2', '3']

def double(n):
  return n * 2

# listの各要素をそれぞれ2倍にする例
assert list(map(double, list_of_numbers)) == [2, 4, 6]
```

**Comment by ghost** [comment]
お返事ありがとうございます。なかなか慣れませんが、理解しました！

話は変わりますが、私はK-means法を使ってグループにおける経路を決定し、それらを統合することで経路を作ろうとしています。

今のところ、グループ化には成功したのですが、各グループに対してgreedyな経路を作らせるのに苦労しています。
各グループに入っている番号が飛び飛びなせいで、unvisited_citiesの扱いと関数distance_from_current_city(to)の扱いがおかしい感じが致します。(原因ちがうかもしれませんよくわからないです....)

もしよろしければ、下のソースコードを見てアドバイスいただけると嬉しいです。
(Python初めてなせいか、Pythonの良さを活かせない書き方で申し訳ないです)

また、統合も若干苦労しております。(ちょっと休憩したらまた取り組みます)

https://github.com/chojuku/google-2015-step-tsp/blob/gh-pages/solver_yuri.py

**Comment by ghost** [comment]
追記:　今悩んでいる話の前者は71行目付近の話です。すみません...

**Comment by hayatoito** [comment]
71行目あたり、コメントしておきますね。

https://github.com/chojuku/google-2015-step-tsp/commit/2149b366ef06ce39a20360289b6731989602d48c#diff-6527156481df29496aea6d570f74c31dR74
