### ISSUE TITLE
最後の最後で型エラー.....

### ISSUE THREAD

**Issue by ghost** [hayatoito/google-2015-step-tsp#13]
@hayatoito を付けてコメント入れたのですが、いまいち自信がないのでここにも貼ります...
https://github.com/chojuku/google-2015-step-tsp/blob/gh-pages/solver_yuri.py

81aa2b4d32897b244a9f507882e67864adf8e43f

(解けないの悔しい....です)

**Comment by hayatoito** [comment]
通知きてますので、自信もってください。:)

エラー内容しか見てませんけど、かるーくコメントしておきました。

https://github.com/chojuku/google-2015-step-tsp/commit/81aa2b4d32897b244a9f507882e67864adf8e43f#commitcomment-11969013
