### ISSUE TITLE
solver_yours.csvの書き込み方

### ISSUE THREAD

**Issue by ghost** [hayatoito/google-2015-step-tsp#9]

**Comment by hayatoito** [comment]
`solutions_yours_n.csv` のことだと理解（であってる？）

README.md の "3. Data Format Specification" に書いてあるフォーマットにしたがってくれるなら、どういうふうにつくろうと自由です。

この `solutions_yours_n.csv` は Visualizer が読み込みます。Visualizer が内部で使用しているCSVパーサの都合上、このようなフォーマットになっています。

きっと、このファイルにスコアの情報もつけたいだろーなーと思うのですが、
（こんな感じ↓）

```
index
0
2
3
1
4
# 33223.2 <= スコア
```

今のところ、Visualizer はこのような余分な情報がはいると `solutions_yours_n.csv` の読み込みに失敗します。将来の課題ということで。（いあ、すぐになおせるとおもうんだけど、いまのところさぼってる...）

**Comment by ghost** [comment]
ありがとうございます。確認してみます！
